# Generated by Django 6.0.2 on 2026-03-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_claim_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='consultation_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='imaging_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='laboratory_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='medicines_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='procedures_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
